name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IS_GITHUB_PAGES: 'true'
      REPO_NAME: 'acce-website'   # <-- must match your repo exactly
      # Mailchimp audience config for static JSONP signup
      # Define these as Repository Variables (Settings → Variables → Repository variables)
      # They are public values from your Mailchimp embed form, not API keys.
      NEXT_PUBLIC_MAILCHIMP_U: ${{ vars.NEXT_PUBLIC_MAILCHIMP_U }}
      NEXT_PUBLIC_MAILCHIMP_ID: ${{ vars.NEXT_PUBLIC_MAILCHIMP_ID }}
      NEXT_PUBLIC_MAILCHIMP_DC: ${{ vars.NEXT_PUBLIC_MAILCHIMP_DC }}
    steps:
      - name: Check out your repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmjs.org/
          npm ci

      - name: Build your site (static export to out/)
        run: npm run build

      - name: Add .nojekyll (needed for _next/)
        run: touch out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
